---
# tasks file for roles/web-role
- name: Create a container
  docker_container:
    name: '{{ docker_container_name }}'
    image: korados/epamexam:8
    detach: true
    hostname: '{{ hostname }}'
    ports:
      - "{{ src_port }}:{{ dst_port }}"
    networks:
      - name: '{{item}}'
  with_items: '{{ docker_net_name }}'
