---
# tasks file for roles/web-role
- name: Create a container
  docker_container:
    name: webapp-container
    image: korados/epamexam:70
    ports:
      - "{{ src_port }}:{{ dst_port }}"
    networks: {{ item }}
    with_items: '{{ docker_net_name }}'
    detach: true
