---
# tasks file for roles/web-role
- name: Create a container
  docker_container:
    name: webapp-container
    image: korados/epamexam:70
    detach: true
    ports:
      - "{{ src_port }}:{{ dst_port }}"
    networks:
      - name: '{{item}}'
  with_items: '{{ docker_net_name }}'
